'use client';

import { Sparkles, X, Check } from 'lucide-react';
import { useAIContext } from '@/framework/context/providers';

const ACTION_LABELS: Record<string, string> = {
  summary:  'Issue Summary',
  subtasks: 'Subtask Breakdown',
  priority: 'Priority Suggestion',
  comment:  'Comment Draft',
};

const ACTION_EMOJI: Record<string, string> = {
  summary: '📋', subtasks: '🔀', priority: '🎯', comment: '💬',
};

/**
 * Plugin: AIConfirmationModal — global overlay that appears whenever the AI
 * has generated a suggestion requiring user confirmation (human-in-the-loop).
 * Reads from AIContext; safe to mount once at the Shell level.
 */
export function AIConfirmationModal() {
  const { pendingAction, isProcessing, confirmAction, dismissAction } = useAIContext();

  if (!pendingAction) return null;

  const label = ACTION_LABELS[pendingAction.action] ?? pendingAction.action;
  const emoji = ACTION_EMOJI[pendingAction.action] ?? '✨';

  return (
    <div className="fixed inset-0 z-50 flex items-end sm:items-center justify-center">
      {/* Backdrop */}
      <div className="absolute inset-0 bg-black/50 backdrop-blur-sm" onClick={dismissAction} />

      {/* Sheet / Dialog */}
      <div className="relative w-full max-w-lg rounded-t-2xl sm:rounded-2xl bg-white shadow-2xl overflow-hidden">
        {/* Header */}
        <div className="flex items-center justify-between px-5 py-4 bg-gradient-to-r from-indigo-50 to-violet-50 border-b border-indigo-100">
          <div className="flex items-center gap-2.5">
            <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-gradient-to-br from-indigo-500 to-violet-600">
              <Sparkles size={15} className="text-white" />
            </div>
            <div>
              <p className="text-[13px] font-bold text-indigo-900">{emoji} AI Copilot · {label}</p>
              <p className="text-[10px] text-indigo-500">Review before applying · source: AI</p>
            </div>
          </div>
          <button onClick={dismissAction} className="text-slate-400 hover:text-slate-600 transition">
            <X size={16} />
          </button>
        </div>

        {/* Suggestions */}
        <div className="px-5 py-4 space-y-2.5 max-h-72 overflow-y-auto">
          {pendingAction.suggestions.map((s, i) => (
            <div key={i} className="flex gap-2.5">
              <div className="mt-1 h-4 w-4 shrink-0 rounded-full bg-indigo-100 flex items-center justify-center text-[9px] font-bold text-indigo-600">
                {i + 1}
              </div>
              <p className="text-[14px] text-slate-700 leading-relaxed flex-1">{s}</p>
            </div>
          ))}
        </div>

        {/* Source attribution note */}
        <div className="px-5 py-2.5 bg-amber-50 border-t border-amber-100">
          <p className="text-[11px] text-amber-700">
            ⚠️ This suggestion was generated by AI. All changes are audited with source attribution.
          </p>
        </div>

        {/* Actions */}
        <div className="flex border-t border-slate-100 divide-x divide-slate-100">
          <button
            onClick={dismissAction}
            className="flex-1 flex items-center justify-center gap-1.5 py-3.5 text-sm font-medium text-slate-500 hover:bg-slate-50 transition"
          >
            <X size={14} />
            Dismiss
          </button>
          <button
            onClick={() => confirmAction()}
            disabled={isProcessing}
            className="flex-1 flex items-center justify-center gap-1.5 py-3.5 text-sm font-semibold text-indigo-600 hover:bg-indigo-50 transition disabled:opacity-50"
          >
            <Check size={14} />
            Apply to Issue
          </button>
        </div>
      </div>
    </div>
  );
}
