import type { User, Workspace, Project, Issue, Comment, AiLog } from './types';

export const mockUsers: User[] = [
  { id: 'u1', name: 'Alex Chen', email: 'alex@acuguard.io' },
  { id: 'u2', name: 'Jordan Lee', email: 'jordan@acuguard.io' },
  { id: 'u3', name: 'Sam Rivera', email: 'sam@acuguard.io' },
  { id: 'u4', name: 'Taylor Kim', email: 'taylor@acuguard.io' },
];

export const mockWorkspaces: Workspace[] = [
  { id: 'ws1', name: 'AcuGuard', slug: 'acuguard', ownerId: 'u1' },
  { id: 'ws2', name: 'Side Projects', slug: 'side-projects', ownerId: 'u1' },
];

export const projects: Project[] = [
  {
    id: 'p1',
    workspaceId: 'ws1',
    name: 'Mobile App',
    key: 'MOB',
    description: 'iOS and Android native applications',
    color: '#4f46e5',
    createdAt: '2024-01-15T00:00:00Z',
  },
  {
    id: 'p2',
    workspaceId: 'ws1',
    name: 'Backend API',
    key: 'API',
    description: 'REST and GraphQL API services',
    color: '#7c3aed',
    createdAt: '2024-01-20T00:00:00Z',
  },
  {
    id: 'p3',
    workspaceId: 'ws1',
    name: 'Design System',
    key: 'DS',
    description: 'Component library and design tokens',
    color: '#db2777',
    createdAt: '2024-02-01T00:00:00Z',
  },
  {
    id: 'p4',
    workspaceId: 'ws1',
    name: 'Infrastructure',
    key: 'INFRA',
    description: 'DevOps and cloud infrastructure',
    color: '#16a34a',
    createdAt: '2024-02-10T00:00:00Z',
  },
];

export const mockIssues: Issue[] = [
  {
    id: 'i1',
    projectId: 'p1',
    title: 'Implement push notification system',
    description: 'Add FCM/APNs integration for real-time push notifications on both platforms.',
    status: 'in_progress',
    priority: 'high',
    assigneeId: 'u1',
    reporterId: 'u2',
    createdAt: '2024-03-01T10:00:00Z',
    updatedAt: '2024-03-05T14:30:00Z',
  },
  {
    id: 'i2',
    projectId: 'p1',
    title: 'Fix offline mode data sync',
    description: 'Local cache gets out of sync when reconnecting after extended offline period.',
    status: 'todo',
    priority: 'high',
    assigneeId: 'u3',
    reporterId: 'u1',
    createdAt: '2024-03-02T09:00:00Z',
    updatedAt: '2024-03-02T09:00:00Z',
  },
  {
    id: 'i3',
    projectId: 'p1',
    title: 'Add biometric authentication',
    description: 'Support Face ID and fingerprint login on supported devices.',
    status: 'todo',
    priority: 'medium',
    assigneeId: 'u2',
    reporterId: 'u4',
    createdAt: '2024-03-03T11:00:00Z',
    updatedAt: '2024-03-03T11:00:00Z',
  },
  {
    id: 'i4',
    projectId: 'p1',
    title: 'Optimize app startup time',
    description: 'Cold start time exceeds 3 seconds on mid-range devices.',
    status: 'done',
    priority: 'medium',
    assigneeId: 'u4',
    reporterId: 'u1',
    createdAt: '2024-02-20T08:00:00Z',
    updatedAt: '2024-03-01T16:00:00Z',
  },
  {
    id: 'i5',
    projectId: 'p2',
    title: 'Rate limiting middleware',
    description: 'Implement per-user and per-endpoint rate limiting to prevent abuse.',
    status: 'in_progress',
    priority: 'high',
    assigneeId: 'u2',
    reporterId: 'u1',
    createdAt: '2024-03-01T09:30:00Z',
    updatedAt: '2024-03-04T11:00:00Z',
  },
  {
    id: 'i6',
    projectId: 'p2',
    title: 'GraphQL subscription support',
    description: 'Add WebSocket-based subscriptions for real-time data updates.',
    status: 'todo',
    priority: 'medium',
    assigneeId: 'u1',
    reporterId: 'u3',
    createdAt: '2024-03-04T13:00:00Z',
    updatedAt: '2024-03-04T13:00:00Z',
  },
  {
    id: 'i7',
    projectId: 'p2',
    title: 'Database query performance audit',
    description: 'Several endpoints have N+1 query problems causing slow responses.',
    status: 'todo',
    priority: 'high',
    reporterId: 'u2',
    createdAt: '2024-03-05T10:00:00Z',
    updatedAt: '2024-03-05T10:00:00Z',
  },
  {
    id: 'i8',
    projectId: 'p3',
    title: 'Dark mode token system',
    description: 'Define semantic color tokens that work across light and dark themes.',
    status: 'in_progress',
    priority: 'medium',
    assigneeId: 'u4',
    reporterId: 'u3',
    createdAt: '2024-03-02T14:00:00Z',
    updatedAt: '2024-03-06T09:00:00Z',
  },
  {
    id: 'i9',
    projectId: 'p3',
    title: 'Accessibility audit',
    description: 'Ensure all components meet WCAG 2.1 AA standards.',
    status: 'done',
    priority: 'high',
    assigneeId: 'u3',
    reporterId: 'u4',
    createdAt: '2024-02-25T10:00:00Z',
    updatedAt: '2024-03-03T15:00:00Z',
  },
  {
    id: 'i10',
    projectId: 'p4',
    title: 'Kubernetes cluster autoscaling',
    description: 'Configure HPA and cluster autoscaler for production workloads.',
    status: 'todo',
    priority: 'low',
    assigneeId: 'u1',
    reporterId: 'u2',
    createdAt: '2024-03-05T16:00:00Z',
    updatedAt: '2024-03-05T16:00:00Z',
  },
];

export const mockComments: Comment[] = [
  {
    id: 'c1',
    issueId: 'i1',
    authorId: 'u2',
    body: 'FCM setup is complete. Working on APNs certificate provisioning now.',
    createdAt: '2024-03-03T10:00:00Z',
  },
  {
    id: 'c2',
    issueId: 'i1',
    authorId: 'u1',
    body: 'APNs certs approved. Starting notification payload schema design.',
    createdAt: '2024-03-04T14:00:00Z',
  },
  {
    id: 'c3',
    issueId: 'i5',
    authorId: 'u2',
    body: 'Using token bucket algorithm. Testing with 100 req/min per user.',
    createdAt: '2024-03-02T11:00:00Z',
  },
  {
    id: 'c4',
    issueId: 'i8',
    authorId: 'u4',
    body: 'Draft token spec is ready for review. See Figma link in description.',
    createdAt: '2024-03-05T09:30:00Z',
  },
];

export const mockAiLogs: AiLog[] = [
  {
    id: 'al1',
    issueId: 'i1',
    action: 'summary',
    input: 'Summarize this issue',
    output: 'Push notification system implementation for FCM and APNs across iOS and Android.',
    confirmedBy: 'u1',
    createdAt: '2024-03-05T12:00:00Z',
  },
  {
    id: 'al2',
    issueId: 'i2',
    action: 'priority',
    input: 'Analyze priority',
    output: 'Recommend upgrading to critical — data loss risk during reconnection.',
    createdAt: '2024-03-05T13:00:00Z',
  },
  {
    id: 'al3',
    issueId: 'i7',
    action: 'subtasks',
    input: 'Break down into subtasks',
    output: '1. Run EXPLAIN ANALYZE on top 20 slow queries\n2. Add missing indexes\n3. Implement DataLoader batching\n4. Add query result caching',
    confirmedBy: 'u2',
    createdAt: '2024-03-05T15:00:00Z',
  },
];
